### PR TITLE
Added Blockchain Info for all coins

### PR DESCRIPTION
**Pull request by PrettyBoyHelios**
# Description

Added Blockchain Info according to the following structure.

type BlockchainInfo struct {
	MaxDiff        float64
	ValidationTime float64
	TxApiUrl       string
}

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added unit tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by eabz** [comment]
Great @PrettyBoyHelios 
Can I get a description on those new additions?
What do you mean with `MaxDiff`and `ValidationTime` Maybe we need to rename those vars to be more self explained. 
Also, I was thinking a little, if we want to confirm a tx informaition based on a txid I think the main source of information should be the hot-wallets. Maybe we need to homologue the txid request to plutus, since using another node can result on invalid information or we want to trust only the hot-wallets.

**Comment by PrettyBoyHelios** [comment]
ValidationTime is Actually BlockValidationTime. I used the same parameters as the previous caronte implementation, couldn't tell MaxDiff meaning or usage. I don't think MaxDiff is ever used in the code.

Changing block validation time name and deleting MaxDiff seems a good solution for me.

**Comment by eabz** [comment]
Modified the CoinFactor a little. 
This will break all our implementations, but seems a good workaround to start categorizing things.

**Comment by PrettyBoyHelios** [comment]
One question, the purpose of the blockexplorer url string was specifically to retrive tx info from the API. Should we change the ExternalSource field or add another one?

**Comment by eabz** [comment]
No, the purpose of the ExternalSource is to use another source to get sync information. 
To get a transaction we should use Plutus. I'll create the endpoint

**Comment by PrettyBoyHelios** [comment]
Oh, now I get it! I'll be waiting for that!

**Comment by eabz** [comment]
@PrettyBoyHelios Here is https://documenter.getpostman.com/view/4345063/SVfUs7CX?version=latest#291c9b51-f868-454b-bb86-a1cc953f208e

**Pull request merged**
